# Generated by Django 6.0 on 2025-12-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='beneficiar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='citizen',
            name='cnp',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='citizen',
            name='data_emitere',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='emitent',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='citizen',
            name='judet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='citizen',
            name='localitate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='citizen',
            name='nr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='citizen',
            name='numar_document_extern',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='citizen',
            name='nume',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='citizen',
            name='prenume',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='citizen',
            name='strada',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='citizen',
            name='telefon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='citizen',
            name='tip_document',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
