# Generated by Django 5.2.9 on 2025-12-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_municipality_superadmincode_admininvite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='municipality',
            field=models.ForeignKey(blank=True, help_text='Daca este setata, template-ul este vizibil doar pentru acea primarie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='core.municipality'),
        ),
    ]
