# Generated by Django 5.2.9 on 2025-12-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documenttemplate_municipality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttemplate',
            name='municipality',
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='municipalities',
            field=models.ManyToManyField(blank=True, help_text='Lasa necompletat pentru a fi disponibil tuturor primariilor', related_name='templates', to='core.municipality'),
        ),
    ]
