# Generated by Django 5.2.9 on 2025-12-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_documenttemplate_municipality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='profile_status',
            field=models.CharField(choices=[('up_to_date', 'Date la zi'), ('pending_validation', 'Se asteapta validare'), ('needs_update', 'Necesita actualizare')], default='up_to_date', max_length=30),
        ),
    ]
