# Generated by Django 5.2.9 on 2025-12-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_citizen_profile_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='email_recuperare',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
