# Generated by Django 5.2.9 on 2025-12-07 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='email_recuperare_pending',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='citizen',
            name='email_recuperare_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_codes', to='core.citizen')),
            ],
        ),
    ]
