# Generated by Django 5.2.9 on 2025-12-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_citizen_email_recuperare_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='cif',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cod identificare fiscala'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='municipality',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='municipality',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='municipality',
            name='extra_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='header_banner',
            field=models.ImageField(blank=True, null=True, upload_to='municipality_headers/'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='header_logo',
            field=models.ImageField(blank=True, null=True, upload_to='municipality_headers/'),
        ),
        migrations.AddField(
            model_name='municipality',
            name='mayor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='municipality',
            name='number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='municipality',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='municipality',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='municipality',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
