# Generated by Django 5.2.9 on 2025-12-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_municipality_cif_municipality_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='dynamic_fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
