# Generated by Django 5.2.9 on 2025-12-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_message_attachment_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read_by_citizen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='read_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
